#!/usr/bin/env python3
# binance_rss.py
# Generates launchpool.xml (RSS 2.0) from Binance CMS API

import datetime, json, requests
from feedgen.feed import FeedGenerator

API = "https://www.binance.com/bapi/composite/v1/public/cms/article/list/query"
BODY = {"type": 1, "catalogId": 48, "pageNo": 1, "pageSize": 20}
HEAD = {
    "User-Agent": "Mozilla/5.0",
    "X-Lang": "zh-CN",
    "X-Platform": "web",
    "X-Channel-Code": "official-site",
}

def fetch_articles():
    params = {"type": 1, "catalogId": 48, "pageNo": 1, "pageSize": 20}
    r = requests.get(API, params=params, headers=HEAD, timeout=15)
    r.raise_for_status()
    return r.json()["data"]["articles"]

def build_feed():
    fg = FeedGenerator()
    fg.title("Binance – 新数字货币及交易对上新")
    fg.link(href="https://www.binance.com/zh-CN/support/announcement/list/48")
    fg.description("Automated feed generated by GitHub Actions")
    fg.language("zh-cn")

    for a in fetch_articles():
        fe = fg.add_entry()
        fe.title(a["title"])
        fe.link(href=f'https://www.binance.com/zh-CN/support/announcement/{a["code"]}')
        fe.guid(a["code"])
        fe.pubDate(datetime.datetime.fromtimestamp(a["releaseDate"] / 1000))

    fg.rss_file("launchpool.xml", pretty=True)

if __name__ == "__main__":
    build_feed()
